//ORG EVENTS
exports.GET_SPECIFIC_ORGANIZATION = "GET_SPECIFIC_ORGANIZATION";
exports.GET_ALL_ORGANIZATIONS = "GET_ALL_ORGANIZATIONS";
exports.GET_SPECIFIC_ORGANIZATIONS = "GET_SPECIFIC_ORGANIZATIONS";
exports.PUT_ORGANIZATION = "PUT_ORGANIZATION";
exports.POST_ORGANIZATION = "POST_ORGANIZATION";
exports.DELETE_ORGANIZATION = "DELETE_ORGANIZATION";

//LOC EVENTS
exports.GET_SPECIFIC_LOCATION = "GET_SPECIFIC_LOCATION";
exports.GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
exports.GET_SPECIFIC_LOCATIONS = "GET_SPECIFIC_LOCATIONS";
exports.PUT_LOCATION = "PUT_LOCATION";
exports.POST_LOCATION = "POST_LOCATION";
exports.DELETE_LOCATION = "DELETE_LOCATION";

//PAR EVENTS
exports.GET_SPECIFIC_PARKING_LOT = "GET_SPECIFIC_PARKING_LOT";
exports.GET_ALL_PARKING_LOTS = "GET_ALL_PARKING_LOTS";
exports.GET_SPECIFIC_PARKING_LOTS = "GET_SPECIFIC_PARKING_LOTS";
exports.PUT_PARKING_LOT = "PUT_PARKING_LOT";
exports.POST_PARKING_LOT = "POST_PARKING_LOT";
exports.DELETE_PARKING_LOT = "DELETE_PARKING_LOT";

//SPOT EVENTS
exports.GET_SPECIFIC_SPOT = "GET_SPECIFIC_SPOT";
exports.GET_ALL_SPOTS = "GET_ALL_SPOTS";
exports.GET_SPECIFIC_SPOTS = "GET_SPECIFIC_SPOTS";
exports.PUT_SPOT = "PUT_SPOT";
exports.POST_SPOT = "POST_SPOT";
exports.DELETE_SPOT = "DELETE_SPOT";